version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: homepage-postgres-db
    env_file:
      - .env.dev
    ports:
      - '5432:5432'
    restart: on-failure
    volumes:
      - postgres-db:/var/lib/postgresql/data
  homepage:
    image: homepage
    container_name: homepage
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env.dev
    command: gunicorn 'app:create_app()' --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
volumes:
  postgres-db:
